analyzer:
  errors:
    must_be_immutable: ignore
    constant_identifier_names: ignore
    camel_case_types: ignore
    library_private_types_in_public_api: ignore
    non_constant_identifier_names: ignore

include: package:flutter_lints/flutter.yaml

linter:
  rules:
